# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_stock
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=200117Nd
spring.datasource.password=200117Nd

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuration du serveur
server.port=8083

# Configuration CORS pour Angular
spring.web.cors.allowed-origins=http://localhost:4200
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
